---
title: "000_testdocument_widetolong"
output: html_document
---

## Library
```{r}
# library(jsonlite)
# library(formr)
# library(psych)
library(stringr)
library(tidyr)
library(dplyr)
library(reshape)
```


```{r}
pw2015_t2 = read.csv("ImportedData/pw2015_t2_select.csv", sep = ";")
pw2015_t2_frauen = read.csv("ImportedData/pw2015_t2_frauen_select.csv", sep = ";")
```


Prepare test data
```{r}
#pw2015_t2_relationships
pw2015_t2_relationship <- left_join(pw2015_t2, pw2015_t2_frauen, by=c("session","short_session"))

pw2015_t2_relationship <- pw2015_t2_relationship %>% mutate(
  "t2_relationship" = derivedVariable(
             "0" = (relationship_f == 1 & relationship_m == 1) | (relationship_f == 1 & is.na(relationship_m) |  
                          (is.na(relationship_f) & relationship_m == 1)),
              "1" = (relationship_f == 2 | relationship_m == 2), .method = "first", .default = 0)) %>% as_tibble()

t2_test <- dplyr::select(pw2015_t2_relationship,short_session,starts_with("relationship1"), starts_with("relationship2") )
  
#How many have both male and female partners simultaneously?
z_1 <- !is.na(t2_test$relationship1_kind_m) & !is.na(t2_test$relationship1_kind_f)
length(z_1[z_1==TRUE])

z_2 <- !is.na(t2_test$relationship2_kind_m) & !is.na(t2_test$relationship2_kind_f)
length(z_2[z_2==TRUE])


t2_test <-  dplyr:: select(t2_test, -relationship1_m_name, -relationship1_f_name, -relationship1_name_m_new, -relationship1_name_f_new,
                           -relationship1_age_m_new, -relationship1_age_f_new, -relationship1_height_m_new, -relationship1_height_f_new,
                           -relationship1_relationship_m_new, -relationship1_relationship_f_new, -relationship1_duration_m_new,
                           -relationship1_duration_f_new) 
t2_test <-  dplyr:: select(t2_test, -relationship2_m_name, -relationship2_f_name, -relationship2_name_m_new, -relationship2_name_f_new,
                           -relationship2_age_m_new, -relationship2_age_f_new, -relationship2_height_m_new, -relationship2_height_f_new,
                           -relationship2_relationship_m_new, -relationship2_relationship_f_new, -relationship2_duration_m_new,
                           -relationship2_duration_f_new) 

```


Problem: participants with both male and female partners at T2
```{r}
##Relationship 1
t2_test <- t2_test %>% dplyr::mutate(
  "relationship3_kind" = derivedVariable(
     "1" = (!is.na(relationship1_kind_m) & !is.na(relationship1_kind_f)),.method = "first", .default = 0))
t2_test$relationship3_kind[t2_test$relationship3_kind == 1] <- t2_test$relationship1_kind_f[t2_test$relationship3_kind == 1]
t2_test$relationship3_kind[t2_test$relationship3_kind == 0] <- NA

t2_test <- t2_test %>% dplyr::mutate(
  "relationship3_start_months" = derivedVariable(
     "1" = (!is.na(relationship1_start_months_m) & !is.na(relationship1_start_months_f)) ,.method = "first", .default = 0))
t2_test$relationship3_start_months[t2_test$relationship3_start_months == 1] <- t2_test$relationship1_start_months_f[t2_test$relationship3_start_months == 1]
t2_test$relationship3_start_months[t2_test$relationship3_start_months == 0] <- NA

t2_test <- t2_test %>% dplyr::mutate(
  "relationship3_start_weeks" = derivedVariable(
     "1" = (!is.na(relationship1_start_weeks_m) & !is.na(relationship1_start_weeks_f)),.method = "first", .default = 0))
t2_test$relationship3_start_weeks[t2_test$relationship3_start_weeks == 1] <- t2_test$relationship1_start_weeks_f[t2_test$relationship3_start_weeks == 1]
t2_test$relationship3_start_weeks[t2_test$relationship3_start_weeks == 0] <- NA

##Relationship 2
t2_test <- t2_test %>% dplyr::mutate(
  "relationship4_kind" = derivedVariable(
     "1" = (!is.na(relationship2_kind_m) & !is.na(relationship2_kind_f)),.method = "first", .default = 0))
t2_test$relationship4_kind[t2_test$relationship4_kind == 1] <- t2_test$relationship2_kind_f[t2_test$relationship4_kind == 1]
t2_test$relationship4_kind[t2_test$relationship4_kind == 0] <- NA

t2_test <- t2_test %>% dplyr::mutate(
  "relationship4_start_months" = derivedVariable(
     "1" = (!is.na(relationship2_start_months_m) & !is.na(relationship2_start_months_f)) ,.method = "first", .default = 0))
t2_test$relationship4_start_months[t2_test$relationship4_start_months == 1] <- t2_test$relationship2_start_months_f[t2_test$relationship4_start_months == 1]
t2_test$relationship4_start_months[t2_test$relationship4_start_months == 0] <- NA

t2_test <- t2_test %>% dplyr::mutate(
  "relationship4_start_weeks" = derivedVariable(
     "1" = (!is.na(relationship2_start_weeks_m) & !is.na(relationship2_start_weeks_f)),.method = "first", .default = 0))
t2_test$relationship4_start_weeks[t2_test$relationship4_start_weeks == 1] <- t2_test$relationship2_start_weeks_f[t2_test$relationship4_start_weeks == 1]
t2_test$relationship4_start_weeks[t2_test$relationship4_start_weeks == 0] <- NA

```

Relationship 1
```{r}
t2_test <- t2_test %>% tidyr::unite(relationship1_kind, relationship1_kind_m, relationship1_kind_f ) %>% unite(relationship1_start_months, relationship1_start_months_m, relationship1_start_months_f) %>% unite(relationship1_start_weeks, relationship1_start_weeks_m, relationship1_start_weeks_f)


t2_test$relationship1_kind <- sub('_NA*','', t2_test$relationship1_kind)
t2_test$relationship1_kind <- sub('NA_*','', t2_test$relationship1_kind)
t2_test[t2_test==""]  <- NA 
t2_test <- t2_test %>% group_by(grepl('_', relationship1_kind)) %>% separate(relationship1_kind, c("relationship1_kind","relationship3_kind"))

t2_test$relationship1_start_months <- sub('_NA*','', t2_test$relationship1_start_months)
t2_test$relationship1_start_months <- sub('NA_*','', t2_test$relationship1_start_months)
t2_test[t2_test==""]  <- NA 
t2_test <- t2_test %>% group_by(grepl('_', relationship1_start_months)) %>% separate(relationship1_start_months, c("relationship1_start_months","relationship3_start_months"))

t2_test$relationship1_start_weeks <- sub('_NA*','', t2_test$relationship1_start_weeks)
t2_test$relationship1_start_weeks <- sub('NA_*','', t2_test$relationship1_start_weeks)
t2_test[t2_test==""]  <- NA 
t2_test <- t2_test %>% group_by(grepl('_', relationship1_start_weeks)) %>% separate(relationship1_start_weeks, c("relationship1_start_weeks","relationship3_start_weeks"))
```

Relationship 2
```{r}
t2_test <- t2_test %>% tidyr::unite(relationship2_kind, relationship2_kind_m, relationship2_kind_f ) %>% unite(relationship2_start_months, relationship2_start_months_m, relationship2_start_months_f) %>% unite(relationship2_start_weeks, relationship2_start_weeks_m, relationship2_start_weeks_f)

t2_test$relationship2_kind <- sub('_NA*','', t2_test$relationship2_kind)
t2_test$relationship2_kind <- sub('NA_*','', t2_test$relationship2_kind)
t2_test[t2_test==""]  <- NA 
t2_test <- t2_test %>% group_by(grepl('_', relationship2_kind)) %>% separate(relationship2_kind, c("relationship2_kind","relationship4_kind"))

t2_test$relationship2_start_months <- sub('_NA*','', t2_test$relationship2_start_months)
t2_test$relationship2_start_months <- sub('NA_*','', t2_test$relationship2_start_months)
t2_test[t2_test==""]  <- NA 
t2_test <- t2_test %>% group_by(grepl('_', relationship2_start_months)) %>% separate(relationship2_start_months, c("relationship2_start_months","relationship4_start_months"))

t2_test$relationship2_start_weeks <- sub('_NA*','', t2_test$relationship2_start_weeks)
t2_test$relationship2_start_weeks <- sub('NA_*','', t2_test$relationship2_start_weeks)
t2_test[t2_test==""]  <- NA 
t2_test <- t2_test %>% group_by(grepl('_', relationship2_start_weeks)) %>% separate(relationship2_start_weeks, c("relationship2_start_weeks","relationship4_start_weeks")) %>% ungroup()
```

Arrange variables in proper order
```{r}
t2_test <- t2_test %>% dplyr::select( -starts_with("grepl"))
  
t2_test <- t2_test %>% dplyr::select(short_session, relationship1_kind, relationship1_start_months, relationship1_start_weeks, relationship2_kind, relationship2_start_months, relationship2_start_weeks, relationship3_kind, relationship3_start_months, relationship3_start_weeks, relationship4_kind, relationship4_start_months, relationship4_start_weeks)

```

Change format from wide to long
```{r}
as.data.frame(t2_test)

t2_testx <- reshape(t2_test, direction='long', 
        varying=c('relationship1_kind', 'relationship1_start_months', 'relationship1_start_weeks', 
        'relationship2_kind', 'relationship2_start_months', 'relationship2_start_weeks', 'relationship3_kind',        
        'relationship3_start_months', 'relationship3_start_weeks', 'relationship4_kind', 'relationship4_start_months',
        'relationship4_start_weeks'), 
        timevar='var',
        times=c('relationship1', 'relationship2', 'relationship3', 'relationship4'),
        v.names=c('kind', 'start_months', 'start_weeks'),
        idvar='short_session')



```


